name: sales_forecasting_env
channels:
  - defaults
dependencies:
  - pandas=1.3.3
  - numpy=1.21.5
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - scikit-learn=0.24.2
  - statsmodels=0.13.1
  - dash=2.0.0
  - ast=0.0.2
